config/routes.rb
Rails.application.routes.draw do
  resources :paints
  resources :user_steps
  resources :handers
  resources :blogcomments
  resources :postcomments
  resources :blogs

  resources :posts do 
    member { post :postlike }
  end
  
  resources :memberships
  resources :groups
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "registrations" }
  resources :users
  root to: "static_pages#home" 
  match '/home' , to: 'static_pages#home', via: 'get'
  match '/faq' , to: 'static_pages#faq', via: 'get'
  match '/thankyou' , to: 'static_pages#thankyou', via: 'get'
  match '/admindashboard' , to: 'static_pages#admindashboard', via: 'get'
  match '/aboutus', to: 'static_pages#aboutus', via: 'get'
  match '/follow' , to: 'relationships#follow', via: 'post'
  match '/unfollow' , to: 'relationships#unfollow', via: 'post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
      if user.has_role? :superadmin
        can :manage, :all
      else
        can :read, :all
        can :manage, Blog if user.has_role?(:blogwriter, Blog)
        can :manage, Post if user.has_role?(:blogwriter, Post)
        can :manage, Group if user.has_role?(:moderator, Group)
        can :manage, Postcomment if user.has_role?(:moderator, Postcomment)
        can :manage, Blogcomment if user.has_role?(:moderator, Blogcomment)
      end
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    belongs_to :group
    mount_uploader :blogimage, BlogimageUploader
end

app/models/blogcomment.rb
class Blogcomment < ApplicationRecord
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/group.rb
class Group < ApplicationRecord
    has_many :memberships
    has_many :users, through: :memberships
    has_many :posts
    has_many :blogs
    mount_uploader :groupprofile, GroupprofileUploader
    mount_uploader :groupcoverimage, GroupcoverimageUploader
end

app/models/hander.rb
class Hander < ApplicationRecord
	resourcify
	has_many :handerusers
  	has_many :users, through: :handerusers
end

app/models/handeruser.rb
class Handeruser < ApplicationRecord
	belongs_to :user
	belongs_to :hander
end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :user
    belongs_to :group, :class_name => "Group"
end

app/models/paint.rb
class Paint < ApplicationRecord
	mount_uploader :homeimage, HomeimageUploader
	mount_uploader :siimage, SiimageUploader
	mount_uploader :suimage, SuimageUploader
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :group
    has_many :postcomments
    mount_uploader :postimage, PostimageUploader
    mount_uploader :postvideo, PostvideoUploader
    markable_as :postlike
end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,
         :omniauthable, omniauth_providers: [:google_oauth2, :facebook]

  has_many :memberships
  has_many :groups, through: :memberships
  has_many :posts
  has_many :blogs
  has_many :postcomments
  has_many :handerusers
  has_many :handers, through: :handerusers
  mount_uploader :profileimage, ProfileimageUploader
  acts_as_marker
  acts_as_followable
  acts_as_follower

  def password_required?
    return false 
    super
  end

  def email_required?
  	return false 
    super
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    # data = access_token.info
    # user = User.where(email: data['email']).first

    # # Uncomment the section below if you want users to be created if they don't exist
    # unless user
    #     user = User.create(name: data['name'],
    #        email: data['email'],
    #        password: Devise.friendly_token[0,20]
    #     )
    # end
    # user
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
end

def self.from_omniauthfacebook(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def home
	@post = Post.new
	@posts = Post.all
	@someblogs = Blog.last(3)
	@postcomment = Postcomment.new
end

def aboutus
	
end

def faq
	
end

def thankyou
	
end

def admindashboard
	@blogs = Blog.last(10)
	@users = User.last(10)
	@groups = Group.last(10)
end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/handers_helper.rb
module HandersHelper
end

app/helpers/paints_helper.rb
module PaintsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/views/static_pages/aboutus.html.erb
<h1>Hello</h1>

app/views/static_pages/admindashboard.html.erb
<style type="text/css">
	
	#sidebar {
	  display: none;
	}

	.headhold {
		background-color: #4a4a4a;
		padding: 30px;
		border-radius: 20px;
		color: white;
	}

	.bogges {
		background-color: #ffffff;
		border-radius: 10px;
		padding: 10px;
		margin-bottom: 10px;
		 -webkit-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.20);
        -moz-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.20);
    box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.20);
	}

	.actionrow {
		border-radius: 10px;
		padding: 10px;
		margin-bottom: 10px;
		 -webkit-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.20);
        -moz-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.20);
    box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.20);
	}

</style>

<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="headhold">
				<h4>Welcome, <%= current_user.name %>.</h4>
				<p style="color: white;">Manage all groups, users and blogs from here. For other admin tasks, you will see special action buttons on posts, comments, blogs and groups.</p>
			</div>
		</div>
	</div>
</div>


<div class="container">
	<div class="row actionrow" style="margin-top: 20px; margin-bottom: 20px; padding: 20px; background-color: white;">
		<div class="col-lg-4">
			<div class="createhold1">
				<span style="font-weight: 500;">Create a group, a blog post, or assign a role to a user.</span>
				
			</div>
		</div>
		<div class="col-lg-2">
			<p style="">
			<a href="/paints/1/edit" class="btn btn-primary">Edit page content</a>
			</p>
		</div>
		<div class="col-lg-2">
			<p style="width: 100%;">
			<a href="/groups/new" class="btn btn-primary" style="width: 100%;">Create Group</a>
			</p>
		</div>
		<div class="col-lg-2">
			<p style="width: 100%;">
			<a href="/blogs/new" class="btn btn-primary" style="width: 100%;">Create Blogs</a>
			</p>
		</div>
		<div class="col-lg-2">
			<p style="width: 100%;">
			<a href="/handers/new" class="btn btn-primary" style="width: 100%;">Role Asigner</a>
			</p>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-12">
			<div class="headhold2">
				
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-4">
			<h5>All Blogs</h5>
			<div class="row">
				<% @blogs.find_all do |blog| %>
				<div class="col-lg-12">
					<div class="bogges">
						<%= blog.title %><br>
						<p style="text-align: right; margin-top: 10px;">
						<%= link_to 'Open', blog, :style => "color: #0080ff; font-weight: 500; font-size: 12px;" %> | 
				        <%= link_to 'Edit', edit_blog_path(blog), :style => "color: #0080ff; font-weight: 500; font-size: 12px;" %> | 
				        <%= link_to 'Delete', blog, :style => "color: red; font-weight: 500; font-size: 12px;", method: :delete, data: { confirm: 'Are you sure?' } %>
				    	</p>
					</div>
				</div>
				<% end %>
			</div>
		</div>

		<div class="col-lg-4">
			<h5>All Groups</h5>
			<div class="row">
				<% @groups.find_all do |group| %>
				<div class="col-lg-12">
					<div class="bogges">
						<%= group.name %>
						<p style="text-align: right; margin-top: 10px;">
						<%= link_to 'Open', group, :style => "color: #0080ff; font-weight: 500; font-size: 12px;" %> | 
				        <%= link_to 'Edit', edit_group_path(group), :style => "color: #0080ff; font-weight: 500; font-size: 12px;" %> | 
				        <%= link_to 'Delete', group, :style => "color: red; font-weight: 500; font-size: 12px;", method: :delete, data: { confirm: 'Are you sure?' } %>
				    	</p>
					</div>
				</div>
				<% end %>
			</div>
		</div>

		<div class="col-lg-4">
			<h5>All Users</h5>
			<div class="row">
				<% @users.find_all do |user| %>
				<div class="col-lg-12">
					<div class="bogges">
						<%= user.email %>
						<p style="text-align: right; margin-top: 10px;">
						<%= link_to 'Open', user, :style => "color: #0080ff; font-weight: 500; font-size: 12px;" %> | 
				        <%= link_to 'Edit', edit_user_path(user), :style => "color: #0080ff; font-weight: 500; font-size: 12px;" %> | 
				        <%= link_to 'Delete', user, :style => "color: red; font-weight: 500; font-size: 12px;", method: :delete, data: { confirm: 'Are you sure?' } %>
				    	</p>
					</div>
				</div>
				<% end %>
			</div>
		</div>

	</div>

</div>

app/views/static_pages/thankyou.html.erb
<style type="text/css">
	
	#sidebar {
    display: none;
  	}
  	
</style>

<br><br><br>
<p style="text-align: center;">
	<img src="https://res.cloudinary.com/nikasemo/image/upload/v1576052324/smiling-emoticon-square-face_eky0ti.png">
</p>
<h1 style="text-align: center;">Thank you for Signing Up!</h1>
<p style="text-align: center; color: #9c1e34;">Welcome to Kuulish! the main place parents around the world come to know what’s cool … Well more like cool -ish! We all find it hard to keep up with new trends, dances, entertainment and even names for the things we did (that our parents hated) when we were young.

This site is the bridge you need to keep up with your kids. You’re welcome!</p>
<br><br>
<p style="text-align: center;">
	<a href="/" class="btn btn-primary">Proceed to Homepage</a>
</p>
<br><br><br>