config/routes.rb
Rails.application.routes.draw do
  resources :paints
  resources :user_steps
  resources :handers
  resources :blogcomments
  resources :postcomments
  resources :blogs

  resources :posts do 
    member { post :postlike }
  end
  
  resources :memberships
  resources :groups
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "registrations" }
  resources :users
  root to: "static_pages#home" 
  match '/home' , to: 'static_pages#home', via: 'get'
  match '/faq' , to: 'static_pages#faq', via: 'get'
  match '/thankyou' , to: 'static_pages#thankyou', via: 'get'
  match '/admindashboard' , to: 'static_pages#admindashboard', via: 'get'
  match '/aboutus', to: 'static_pages#aboutus', via: 'get'
  match '/follow' , to: 'relationships#follow', via: 'post'
  match '/unfollow' , to: 'relationships#unfollow', via: 'post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/paint.rb
class Paint < ApplicationRecord
	mount_uploader :homeimage, HomeimageUploader
	mount_uploader :siimage, SiimageUploader
	mount_uploader :suimage, SuimageUploader
end

app/controllers/paints_controller.rb
class PaintsController < ApplicationController
  before_action :set_paint, only: [:show, :edit, :update, :destroy]

  # GET /paints
  # GET /paints.json
  def index
    @paints = Paint.all
  end

  # GET /paints/1
  # GET /paints/1.json
  def show
  end

  # GET /paints/new
  def new
    @paint = Paint.new
  end

  # GET /paints/1/edit
  def edit
  end

  # POST /paints
  # POST /paints.json
  def create
    @paint = Paint.new(paint_params)

    respond_to do |format|
      if @paint.save
        format.html { redirect_to "/admindashboard", notice: 'Successfully created.' }
        format.json { render :show, status: :created, location: @paint }
      else
        format.html { render :new }
        format.json { render json: @paint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paints/1
  # PATCH/PUT /paints/1.json
  def update
    respond_to do |format|
      if @paint.update(paint_params)
        format.html { redirect_to "/admindashboard", notice: 'Edit was successfully made.' }
        format.json { render :show, status: :ok, location: @paint }
      else
        format.html { render :edit }
        format.json { render json: @paint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paints/1
  # DELETE /paints/1.json
  def destroy
    @paint.destroy
    respond_to do |format|
      format.html { redirect_to paints_url, notice: 'Paint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paint
      @paint = Paint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paint_params
      params.require(:paint).permit(:hometitle, :homedescription, :sutitle, :sudescription, :sitext, :sidescription, :homeimage, :siimage, :suimage)
    end
end

app/helpers/paints_helper.rb
module PaintsHelper
end

app/views/paints/_form.html.erb
<%= form_for(paint) do |f| %>
  <% if paint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paint.errors.count, "error") %> prohibited this paint from being saved:</h2>

      <ul>
      <% paint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <hr>
  <h3>Home Title</h3>

  <div class="form-group">
    <%= f.label :hometitle %>
    <%= f.text_area :hometitle , :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :homedescription %>
    <%= f.text_area :homedescription , :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :homeimage %>
    <%= f.file_field :homeimage , :class => "form-control" %>
  </div>

  <hr>
  <h3>Sign Up</h3>

  <div class="form-group">
    <%= f.label :sutitle %>
    <%= f.text_field :sutitle , :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :sudescription %>
    <%= f.text_area :sudescription , :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :suimage %>
    <%= f.file_field :suimage , :class => "form-control" %>
  </div>

<hr>
<h3>Sign In</h3>
  <div class="form-group">
    <%= f.label :sitext %>
    <%= f.text_field :sitext , :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :sidescription %>
    <%= f.text_area :sidescription , :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :siimage %>
    <%= f.file_field :siimage , :class => "form-control" %>
  </div>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paints/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-8">
			<h1>Edit Prefs</h1>

			<%= render 'form', paint: @paint %>

		</div>
	</div>
</div>

app/views/paints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paints</h1>

<table>
  <thead>
    <tr>
      <th>Hometitle</th>
      <th>Homedescription</th>
      <th>Sutitle</th>
      <th>Sudescription</th>
      <th>Sitext</th>
      <th>Sidescription</th>
      <th>Homeimage</th>
      <th>Siimage</th>
      <th>Suimage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paints.each do |paint| %>
      <tr>
        <td><%= paint.hometitle %></td>
        <td><%= paint.homedescription %></td>
        <td><%= paint.sutitle %></td>
        <td><%= paint.sudescription %></td>
        <td><%= paint.sitext %></td>
        <td><%= paint.sidescription %></td>
        <td><%= paint.homeimage %></td>
        <td><%= paint.siimage %></td>
        <td><%= paint.suimage %></td>
        <td><%= link_to 'Show', paint %></td>
        <td><%= link_to 'Edit', edit_paint_path(paint) %></td>
        <td><%= link_to 'Destroy', paint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paint', new_paint_path %>

app/views/paints/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-8">
			<h1>Edit Prefs</h1>

			<%= render 'form', paint: @paint %>

			
		</div>
	</div>
</div>

app/views/paints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hometitle:</strong>
  <%= @paint.hometitle %>
</p>

<p>
  <strong>Homedescription:</strong>
  <%= @paint.homedescription %>
</p>

<p>
  <strong>Sutitle:</strong>
  <%= @paint.sutitle %>
</p>

<p>
  <strong>Sudescription:</strong>
  <%= @paint.sudescription %>
</p>

<p>
  <strong>Sitext:</strong>
  <%= @paint.sitext %>
</p>

<p>
  <strong>Sidescription:</strong>
  <%= @paint.sidescription %>
</p>

<p>
  <strong>Homeimage:</strong>
  <%= @paint.homeimage %>
</p>

<p>
  <strong>Siimage:</strong>
  <%= @paint.siimage %>
</p>

<p>
  <strong>Suimage:</strong>
  <%= @paint.suimage %>
</p>

<%= link_to 'Edit', edit_paint_path(@paint) %> |
<%= link_to 'Back', paints_path %>