config/routes.rb
Rails.application.routes.draw do
  resources :paints
  resources :user_steps
  resources :handers
  resources :blogcomments
  resources :postcomments
  resources :blogs

  resources :posts do 
    member { post :postlike }
  end
  
  resources :memberships
  resources :groups
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "registrations" }
  resources :users
  root to: "static_pages#home" 
  match '/home' , to: 'static_pages#home', via: 'get'
  match '/faq' , to: 'static_pages#faq', via: 'get'
  match '/thankyou' , to: 'static_pages#thankyou', via: 'get'
  match '/admindashboard' , to: 'static_pages#admindashboard', via: 'get'
  match '/aboutus', to: 'static_pages#aboutus', via: 'get'
  match '/follow' , to: 'relationships#follow', via: 'post'
  match '/unfollow' , to: 'relationships#unfollow', via: 'post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hander.rb
class Hander < ApplicationRecord
	resourcify
	has_many :handerusers
  	has_many :users, through: :handerusers
end

app/controllers/handers_controller.rb
class HandersController < ApplicationController
  before_action :set_hander, only: [:show, :edit, :update, :destroy]

  # GET /handers
  # GET /handers.json
  def index
    @handers = Hander.all
  end

  # GET /handers/1
  # GET /handers/1.json
  def show
  end

  # GET /handers/new
  def new
    @hander = Hander.new
  end

  # GET /handers/1/edit
  def edit
  end

  # POST /handers
  # POST /handers.json
  def create
    @hander = Hander.new(hander_params)

    respond_to do |format|
      handeruserid = @hander.users.first.id
      handername = @hander.name
      @user = User.find(handeruserid)
      @roleforuser = Role.find_by_name(handername)
      @user.add_role handername
      if @hander.save
        format.html { redirect_to "/admindashboard", notice: 'Role Successfully Asigned' }
        format.json { render :show, status: :created, location: @hander }
      else
        format.html { render :new }
        format.json { render json: @hander.errors, status: :unprocessable_entity }
      end
    end
    authorize! :create, @hander
  end

  # PATCH/PUT /handers/1
  # PATCH/PUT /handers/1.json
  def update
    respond_to do |format|
      if @hander.update(hander_params)
        format.html { redirect_to @hander, notice: 'Hander was successfully updated.' }
        format.json { render :show, status: :ok, location: @hander }
      else
        format.html { render :edit }
        format.json { render json: @hander.errors, status: :unprocessable_entity }
      end
    end
    authorize! :update, @hander
  end

  # DELETE /handers/1
  # DELETE /handers/1.json
  def destroy
    @hander.destroy
    respond_to do |format|
      format.html { redirect_to handers_url, notice: 'Hander was successfully destroyed.' }
      format.json { head :no_content }
    end
    authorize! :destroy, @hander
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hander
      @hander = Hander.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hander_params
      params.require(:hander).permit(:name, :user_ids)
    end
end

app/helpers/handers_helper.rb
module HandersHelper
end

app/views/handers/_form.html.erb
<%= form_for(hander) do |f| %>
  <% if hander.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hander.errors.count, "error") %> prohibited this hander from being saved:</h2>

      <ul>
      <% hander.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>

  <div class="form-group">
    <label>Select role to assign</label><br>
        <select class="select" name="hander[name]" id="hander_name" style="width: 100%;">
          <option name="hander[name]" id="hander_name" value="superadmin">Super Admin</option>
          <option name="hander[name]" id="hander_name" value="blogwriter">Blog writer</option>
          <option name="hander[name]" id="hander_name" value="moderator">Moderator</option>
          <option name="hander[name]" id="hander_name" value="user">User</option>
        </select>
      </div>

  <div class="form-group">
    <label>Select User</label><br>
   <%= f.collection_select :user_ids, User.all, :id, :email, {prompt: "Select User"}, 
    {:required => true, :class => "select", style: "width: 100%;"} %>
  </div>

  <div class="form-group">
    <%= f.submit "Assign Role", :class => "btn btn-success" %>
  </div>
<% end %>

<script type="text/javascript">

$( document ).ready(function() {
 $('.select').select2();
});

</script>

app/views/handers/edit.html.erb
<h1>Editing Hander</h1>

<%= render 'form', hander: @hander %>

<%= link_to 'Show', @hander %> |
<%= link_to 'Back', handers_path %>

app/views/handers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Handers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @handers.each do |hander| %>
      <tr>
        <td><%= hander.name %></td>
        <td><%= link_to 'Show', hander %></td>
        <td><%= link_to 'Edit', edit_hander_path(hander) %></td>
        <td><%= link_to 'Destroy', hander, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hander', new_hander_path %>

app/views/handers/new.html.erb
<h1>New Hander</h1>

<%= render 'form', hander: @hander %>

<%= link_to 'Back', handers_path %>

app/views/handers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hander.name %>
</p>

<%= link_to 'Edit', edit_hander_path(@hander) %> |
<%= link_to 'Back', handers_path %>