config/routes.rb
Rails.application.routes.draw do
  resources :paints
  resources :user_steps
  resources :handers
  resources :blogcomments
  resources :postcomments
  resources :blogs

  resources :posts do 
    member { post :postlike }
  end
  
  resources :memberships
  resources :groups
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', :registrations => "registrations" }
  resources :users
  root to: "static_pages#home" 
  match '/home' , to: 'static_pages#home', via: 'get'
  match '/faq' , to: 'static_pages#faq', via: 'get'
  match '/thankyou' , to: 'static_pages#thankyou', via: 'get'
  match '/admindashboard' , to: 'static_pages#admindashboard', via: 'get'
  match '/aboutus', to: 'static_pages#aboutus', via: 'get'
  match '/follow' , to: 'relationships#follow', via: 'post'
  match '/unfollow' , to: 'relationships#unfollow', via: 'post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blogcomment.rb
class Blogcomment < ApplicationRecord
end

app/controllers/blogcomments_controller.rb
class BlogcommentsController < ApplicationController
  before_action :set_blogcomment, only: [:show, :edit, :update, :destroy]

  # GET /blogcomments
  # GET /blogcomments.json
  def index
    @blogcomments = Blogcomment.all
  end

  # GET /blogcomments/1
  # GET /blogcomments/1.json
  def show
  end

  # GET /blogcomments/new
  def new
    @blogcomment = Blogcomment.new
  end

  # GET /blogcomments/1/edit
  def edit
  end

  # POST /blogcomments
  # POST /blogcomments.json
  def create
    @blogcomment = Blogcomment.new(blogcomment_params)

    respond_to do |format|
      if @blogcomment.save
        format.html { redirect_to @blogcomment, notice: 'Blogcomment was successfully created.' }
        format.json { render :show, status: :created, location: @blogcomment }
      else
        format.html { render :new }
        format.json { render json: @blogcomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogcomments/1
  # PATCH/PUT /blogcomments/1.json
  def update
    respond_to do |format|
      if @blogcomment.update(blogcomment_params)
        format.html { redirect_to @blogcomment, notice: 'Blogcomment was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogcomment }
      else
        format.html { render :edit }
        format.json { render json: @blogcomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogcomments/1
  # DELETE /blogcomments/1.json
  def destroy
    @blogcomment.destroy
    respond_to do |format|
      format.html { redirect_to blogcomments_url, notice: 'Blogcomment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogcomment
      @blogcomment = Blogcomment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogcomment_params
      params.require(:blogcomment).permit(:body, :bolg_id)
    end
end

app/helpers/blogcomments_helper.rb
module BlogcommentsHelper
end

app/views/blogcomments/_form.html.erb
<%= form_for(blogcomment) do |f| %>
  <% if blogcomment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blogcomment.errors.count, "error") %> prohibited this blogcomment from being saved:</h2>

      <ul>
      <% blogcomment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :bolg_id %>
    <%= f.number_field :bolg_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogcomments/edit.html.erb
<h1>Editing Blogcomment</h1>

<%= render 'form', blogcomment: @blogcomment %>

<%= link_to 'Show', @blogcomment %> |
<%= link_to 'Back', blogcomments_path %>

app/views/blogcomments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogcomments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Bolg</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogcomments.each do |blogcomment| %>
      <tr>
        <td><%= blogcomment.body %></td>
        <td><%= blogcomment.bolg_id %></td>
        <td><%= link_to 'Show', blogcomment %></td>
        <td><%= link_to 'Edit', edit_blogcomment_path(blogcomment) %></td>
        <td><%= link_to 'Destroy', blogcomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogcomment', new_blogcomment_path %>

app/views/blogcomments/new.html.erb
<h1>New Blogcomment</h1>

<%= render 'form', blogcomment: @blogcomment %>

<%= link_to 'Back', blogcomments_path %>

app/views/blogcomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @blogcomment.body %>
</p>

<p>
  <strong>Bolg:</strong>
  <%= @blogcomment.bolg_id %>
</p>

<%= link_to 'Edit', edit_blogcomment_path(@blogcomment) %> |
<%= link_to 'Back', blogcomments_path %>